require 'parser/current'
#require 'ruby_parser'
require 'opal'
 
desc "Build our app to build.js"
task :build do
  Opal::Processor.source_map_enabled = false
  Opal.append_path File.dirname(__FILE__) + '/Libs/Parser'
  Opal.append_path File.dirname(__FILE__) + '/Libs/ast'
  #Opal.append_path '/Users/diogo/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/ruby_parser-3.6.2/lib'
  env = Opal::Environment.new
  env.append_path "app"

  File.open("build.js", "w+") do |out|
    out << env["application"].to_s
  end
end